// Auto-generated by generate_prob_maps.lua from 260 Drum Machine Patterns
// Source: https://ia800700.us.archive.org/2/items/260DrumMachinePatterns/
//
// Each value is 0-255: probability of a hit at that step.
// Threshold with density knob: hit fires when prob > (1.0 - density) * 255

#ifndef PIXELSYNTH_RHYTHM_PROB_MAPS_H
#define PIXELSYNTH_RHYTHM_PROB_MAPS_H

#include <stdint.h>

typedef struct {
    uint8_t kick[16];
    uint8_t snare[16];
    uint8_t hihat[16];
    uint8_t perc[16];
    uint8_t accent[16];
    int length;
    int swingAmount;
    int recommendedBpm;
} RhythmProbMap;

typedef enum {
    PROB_BALLAD = 0,
    PROB_BASIC = 1,
    PROB_BOSSA_NOVA = 2,
    PROB_CHA_CHA = 3,
    PROB_DISCO = 4,
    PROB_DNB = 5,
    PROB_ELECTRO = 6,
    PROB_ENDINGS = 7,
    PROB_FUNK = 8,
    PROB_HIP_HOP = 9,
    PROB_HOUSE = 10,
    PROB_LATIN = 11,
    PROB_MARCH = 12,
    PROB_POP = 13,
    PROB_R_B = 14,
    PROB_REGGAE = 15,
    PROB_ROCK = 16,
    PROB_SHUFFLE = 17,
    PROB_SKA = 18,
    PROB_STANDARD_BREAKS = 19,
    PROB_WALTZ = 20,
    // Hand-authored styles (not from source data)
    PROB_JAZZ = 21,
    PROB_BRUSH_JAZZ = 22,
    PROB_WALTZ_JAZZ = 23,
    PROB_LOFI = 24,
    PROB_JANGLE = 25,
    PROB_SNES = 26
} ProbMapStyle;

#define PROB_MAP_COUNT 27

static const char* probMapNames[PROB_MAP_COUNT] = {
    "Ballad",
    "Basic",
    "Bossa Nova",
    "Cha-Cha",
    "Disco",
    "DnB",
    "Electro",
    "Endings",
    "Funk",
    "Hip Hop",
    "House",
    "Latin",
    "March",
    "Pop",
    "R&B",
    "Reggae",
    "Rock",
    "Shuffle",
    "Ska",
    "Standard Breaks",
    "Waltz",
    "Jazz",
    "Brush Jazz",
    "Waltz Jazz",
    "Lo-fi",
    "Jangle",
    "SNES",
};

// Per-style suggested drum preset indices (from instrument_presets.h)
// {kick, snare, hihat, perc} — -1 means "keep current preset"
// Preset indices: 24=808 Kick, 25=808 Snare, 26=808 Clap, 27=808 CH, 28=808 OH,
// 29=808 Tom, 30=Rimshot, 31=Cowbell, 36=Clave, 37=Maracas,
// 66=Ride, 67=Brush Snare, 68=Crash, 69=Shaker, 70=Tambourine,
// 71=Bongo Hi, 73=Conga Hi, 75=Timbales, 76=Woodblock, 77=Agogo Hi
static const int probMapDrumPresets[PROB_MAP_COUNT][4] = {
    [PROB_BALLAD]          = {-1, -1, -1, 26},    // clap
    [PROB_BASIC]           = {-1, -1, -1, 26},    // clap
    [PROB_BOSSA_NOVA]      = {-1, -1, -1, 36},    // clave
    [PROB_CHA_CHA]         = {-1, -1, -1, 31},    // cowbell
    [PROB_DISCO]           = {-1, -1, -1, 26},    // clap
    [PROB_DNB]             = {-1, -1, -1, 26},    // clap
    [PROB_ELECTRO]         = {-1, -1, -1, 26},    // clap
    [PROB_ENDINGS]         = {-1, -1, -1, 26},    // clap
    [PROB_FUNK]            = {-1, -1, -1, 30},    // rimshot
    [PROB_HIP_HOP]         = {-1, -1, -1, 26},    // clap
    [PROB_HOUSE]           = {-1, -1, -1, 26},    // clap
    [PROB_LATIN]           = {-1, -1, -1, 31},    // cowbell
    [PROB_MARCH]           = {-1, -1, -1, 68},    // crash
    [PROB_POP]             = {-1, -1, -1, 70},    // tambourine
    [PROB_R_B]             = {-1, -1, -1, 26},    // clap
    [PROB_REGGAE]          = {-1, -1, -1, 30},    // rimshot
    [PROB_ROCK]            = {-1, -1, -1, 26},    // clap
    [PROB_SHUFFLE]         = {-1, -1, -1, 26},    // clap
    [PROB_SKA]             = {-1, -1, -1, 30},    // rimshot
    [PROB_STANDARD_BREAKS] = {-1, -1, -1, 26},    // clap
    [PROB_WALTZ]           = {-1, -1, -1, 26},    // clap
    [PROB_JAZZ]            = {-1, -1, 66, 66},     // ride on hihat + perc
    [PROB_BRUSH_JAZZ]      = {-1, 67, 66, 66},     // brush snare, ride on hihat + perc
    [PROB_WALTZ_JAZZ]      = {-1, -1, 66, 66},     // ride on hihat + perc
    [PROB_LOFI]            = {-1, -1, -1, 69},     // shaker
    [PROB_JANGLE]          = {-1, -1, -1, 66},     // ride on perc
    [PROB_SNES]            = {-1, -1, -1, 68},     // crash
};

static const RhythmProbMap probMaps[PROB_MAP_COUNT] = {
    // Ballad (33 source patterns: Measure A, Measure B, Break, Measure A, Measure B, Break, Measure A, Measure B, )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {244, 77, 48, 22, 48, 36,126,147,160, 22,133,  0, 22, 95, 86, 48},
        .snare  = {  0,  0, 36, 58,204,  0, 48, 22, 77, 36,  0, 22,180, 36, 48, 48},
        .hihat  = {227, 77,227, 86,210, 95,210, 77,204, 77,198, 58,198,103,192, 58},
        .perc   = { 22, 36, 22,  0,  0,  0, 36, 36, 58, 22, 86, 58, 77, 68, 77, 58},
        .accent = { 36,  0,  0,  0, 58, 22,  0,  0, 36,  0,  0, 22, 68, 36,  0, 22},
        .length = 16, .swingAmount = 0, .recommendedBpm = 70
    },
    // Basic (5 source patterns: ONE AND SEVEN & FIVE AND THIRTEEN, BOOTS N’ CATS, TINY HOUSE, GOOD TO GO, HIP )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0, 83, 83, 83,  0,178, 83,134,  0, 83,  0, 83,  0, 83,  0},
        .snare  = {  0,  0,  0,  0,218,  0,  0,  0,  0,  0,  0,  0,218,  0,  0,  0},
        .hihat  = {134,  0,178,  0,134,  0,178,  0,134,  0,178,  0,134, 83,134,  0},
        .perc   = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Bossa Nova (16 source patterns: BOSSANOVA A, Measure A, Measure B, Break, Measure A, Measure B, Break, Bossa1, B)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {208,  0, 37, 37, 59, 37,184, 59,196,  0,  0, 37, 37,  0,208, 37},
        .snare  = {170,  0,143, 59, 97, 37,157, 37, 97,  0,143, 79, 79, 37, 97, 37},
        .hihat  = { 97, 37,113, 37,170, 37, 97, 37, 97, 37, 97, 59,184, 37, 97, 37},
        .perc   = {143,  0,184,  0,128,  0,196,  0,170,  0,157,  0,157, 37,157,  0},
        .accent = { 37,  0, 37,  0,113,  0,  0,  0, 37,  0,  0, 37,143,  0,  0,  0},
        .length = 16, .swingAmount = 3, .recommendedBpm = 130
    },
    // Cha-Cha (9 source patterns: Measure A, Measure B, Break, ChaCha1, ChaCha2, ChaCha3, ChaChaBreak1, ChaChaBrea)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {169,  0,  0,  0,  0,  0,169,  0,145,  0,  0,  0,  0,  0,192,  0},
        .snare  = {  0,  0, 55,  0,  0,  0,118,  0,  0,  0, 55,  0, 55,  0,  0,  0},
        .hihat  = { 89,  0, 55,  0,169,  0, 89,  0, 89,  0, 55,  0,192,  0, 89,  0},
        .perc   = {192,  0,145, 55,214, 55,145,118,214,  0,118, 89,255, 89,235, 55},
        .accent = {  0,  0,  0,  0, 55,  0, 55, 55,  0,  0, 55,  0, 89, 55,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Disco (37 source patterns: Measure A, Measure B, Break, Measure A, Measure B, Break, Measure A, Measure B, )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {215,  0, 33, 20,235,  0, 20, 33,220,  0, 33, 33,220, 20,  0, 20},
        .snare  = { 80, 54,109, 44,250, 44, 87, 71,102, 80,136, 95,240, 54, 54, 44},
        .hihat  = {183,160,215,172,109,129,194,148,154,129,188,129,116,116,188,142},
        .perc   = { 87,  0, 80, 44,102,  0, 71, 44,123, 44, 80, 71,129, 63,102, 87},
        .accent = { 20,  0,  0,  0, 33,  0,  0,  0, 33,  0,  0,  0, 33,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // DnB (9 source patterns: DRUM AND BASS 1 - A, DRUM AND BASS 1 - B, DRUM AND BASS 2 - A, DRUM AND BASS 2 -)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {214, 55,118, 55, 55,  0, 55,118, 55,118,192, 89,  0,  0,  0, 89},
        .snare  = {  0, 55,  0,  0,255,  0,  0, 89,  0, 89, 55,  0,214,  0, 89,  0},
        .hihat  = {255, 55,255, 55,255, 55,255, 89,255, 89,255, 55,255, 55,255, 89},
        .perc   = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 170
    },
    // Electro (20 source patterns: TECHNO, DUBSTEP - A, DUBSTEP - B, DUBSTEP - RATCHETED, UK GARAGE - A, UK GARAGE )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0,  0, 51, 31,  0,189,  0, 97, 51,134, 83, 31, 97, 51,  0},
        .snare  = {  0, 31,  0,  0,237,  0,  0, 51, 51,  0,  0,  0,237, 51,  0, 31},
        .hihat  = {110,110,178,110,122, 83,178,110,110, 97,134,134,110,122,157,122},
        .perc   = {  0,  0,  0,  0, 51, 51,  0,  0,  0,  0,  0, 51, 51,  0,  0,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 130
    },
    // Endings (5 source patterns: Measure A, Measure B, Ending1, Ending2, Ending3)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {178,  0,  0,  0,  0,  0,  0,  0,134,  0,  0,  0,  0,  0,  0,  0},
        .snare  = { 83, 83,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .hihat  = {134,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .perc   = { 83,  0,  0, 83, 83,  0, 83,  0,134,  0,  0,  0,  0,  0,  0,  0},
        .accent = {134,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Funk (159 source patterns: AMEN BREAK - A, AMEN BREAK - B, AMEN BREAK - C, AMEN BREAK - D, THE FUNKY DRUMME)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {215, 51,110,109, 66, 66, 72,102,132, 77,117,130, 76, 74, 88, 64},
        .snare  = { 39, 90, 66, 72,212, 87, 77,138, 68,126, 79, 76,182, 83, 90, 97},
        .hihat  = {142, 53,115, 68,113, 74,112, 60,121, 62,105, 64,112, 55,110, 53},
        .perc   = {130, 53,132, 51,130, 70,132, 81,139, 79,135, 68,139, 74,139, 64},
        .accent = { 23, 16, 12, 26, 39, 29, 23, 26, 16, 29, 19, 19, 55, 42, 44, 23},
        .length = 16, .swingAmount = 4, .recommendedBpm = 100
    },
    // Hip Hop (20 source patterns: Boombap1, MIAMI BASS - A, MIAMI BASS - B, SALLY, unnamed, ROCK THE PLANET, HIP H)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {237,  0,110, 68, 31,  0,122,134,134, 83,157,110, 31, 68, 51, 97},
        .snare  = {  0,  0,  0,  0,228,  0,  0,  0, 51, 31,  0,  0,228,  0,  0,  0},
        .hihat  = {146, 31,146, 83,157, 31,157, 83,157, 31,146, 83,146, 51,157, 83},
        .perc   = { 31,  0,  0,  0,  0,  0, 31,  0,  0,  0, 31,  0,  0,  0, 31,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 6, .recommendedBpm = 90
    },
    // House (10 source patterns: HOUSE, HOUSE 2, BRIT HOUSE, FRENCH HOUSE, DIRTY HOUSE, DEEP HOUSE, DEEPER HOUSE,)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0, 51, 83,218,  0, 83,  0,255,  0, 51, 83,218,  0, 83, 51},
        .snare  = { 83,110,110, 83,255, 83, 83, 83,110,110,110, 83,255, 83, 83, 83},
        .hihat  = {134,157,255,157,134,157,218,199,134,178,255,157,157,157,218,157},
        .perc   = {110, 83,134, 83, 83, 51,110,110,110, 83,134, 51, 83, 51,110, 83},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 124
    },
    // Latin (63 source patterns: SON CLAVE, RUMBA, BOSSA NOVA, BOUTON, GAHU, SHIKO, SOUKOUS, Measure A, Measure B)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {223,  0,  0,102,152,  0, 30,102,211,  0, 55,102,159, 14, 84,102},
        .snare  = {102, 75,130,134, 75, 65,141, 65, 84, 55, 98, 84,122, 55, 93, 43},
        .hihat  = {134, 49,145,110,134, 23,162, 37,130, 23,152, 43,145, 30,159, 37},
        .perc   = {162, 37,126,118,145, 84,162,122,159, 89,186,110,162, 93,176,126},
        .accent = { 49,  0, 43, 23, 49,  0, 43, 30, 49,  0, 55, 30, 70, 23, 65, 30},
        .length = 16, .swingAmount = 0, .recommendedBpm = 100
    },
    // March (4 source patterns: March1, March2, MarchBreak1, MarchBreak2)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {208,  0, 97,  0,208,  0, 97,  0,208,  0, 97,  0,208,  0, 97,  0},
        .snare  = {208,  0,208,157,157, 97,157,157,208, 97,208,157,157,157,208,157},
        .hihat  = {  0,  0,208,  0,  0,  0,208,  0,  0,  0,208,  0,  0,  0,157,  0},
        .perc   = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 97,  0,  0,  0, 97,  0},
        .accent = {157,  0,  0,  0,157,  0, 97,  0,157,  0,  0, 97,157,  0, 97,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Pop (33 source patterns: Measure A, Measure B, Break, Measure A, Measure B, Break, Measure A, Measure B, )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {222, 77,126, 86, 58, 95,111, 95,154, 86,140,118, 68,118, 86, 95},
        .snare  = { 68, 36, 58, 95,173,  0, 68, 68, 77, 36, 86, 48,192, 48, 58, 48},
        .hihat  = {204, 48,140, 48,186, 48,140, 77,192, 48,140, 48,186, 58,140, 68},
        .perc   = { 36,  0, 22, 22, 48, 22, 36, 22, 58, 48,  0, 48, 48, 58, 48, 22},
        .accent = { 48,  0,  0, 48,147,  0, 36, 22,  0, 36,  0, 22,160, 36, 22, 22},
        .length = 16, .swingAmount = 0, .recommendedBpm = 110
    },
    // R&B (33 source patterns: Measure A, Measure B, Break, Measure A, Measure B, Break, Measure A, Measure B, )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {227, 58,160,133, 48, 68, 68,147,133, 95,160,147, 58,140, 86, 58},
        .snare  = { 48, 58, 68, 48,210, 58, 58,118, 48,103, 58, 68,198, 58, 77, 95},
        .hihat  = {192, 58,192, 86,192, 58,186, 77,180, 58,192, 68,186, 58,186, 68},
        .perc   = { 48,  0, 48,  0, 48, 48, 48, 36, 68, 36, 68,  0, 68, 22, 77, 36},
        .accent = {  0,  0,  0,  0, 95,  0,  0,  0, 36,  0,  0,  0, 86,  0, 22,  0},
        .length = 16, .swingAmount = 3, .recommendedBpm = 95
    },
    // Reggae (32 source patterns: HALF DROP, ONE DROP, TWO DROP, STEPPERS, REGGAETON, Measure A, Measure B, Break,)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {157,  0, 37, 37,143,  0, 49,  0,157, 23, 59, 37,164,  0, 79,  0},
        .snare  = { 70, 23, 88, 70,113,  0,105, 49,121, 37, 59, 49,128, 37, 79, 49},
        .hihat  = {170, 70,190,121,170, 70,196, 97,157, 49,208, 88,170, 49,232, 70},
        .perc   = {  0,  0, 23, 37, 37, 37, 70, 49, 79, 49, 79, 37, 59, 23,  0,  0},
        .accent = { 49,  0,  0,  0, 59,  0,  0,  0, 59,  0, 23,  0, 97, 37, 59,  0},
        .length = 16, .swingAmount = 2, .recommendedBpm = 80
    },
    // Rock (58 source patterns: ROCK 1, ROCK 2, ROCK 3, ROCK 4, Measure A, Measure B, Break, Measure A, Measure )
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {243,  0, 90, 32, 39, 46,108, 46,210,  0,129, 15, 46, 15, 74, 39},
        .snare  = { 69, 39, 85, 39,227, 39,121, 58, 46, 46, 69, 24,207, 46, 74, 69},
        .hihat  = {213, 39,175, 52,200, 39,168, 39,190, 39,161, 39,193, 39,172, 39},
        .perc   = { 64,  0, 52, 24, 80, 24, 80, 32,104, 46, 85, 52, 80, 64, 85, 32},
        .accent = { 69,  0, 24, 15,141,  0, 80, 24, 58, 15, 52, 24,175,  0, 58, 39},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Shuffle (3 source patterns: Boogie1, Boogie2, Boogie3)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0,  0,192,  0,  0,  0,118,255,  0,  0,255,  0,  0,  0,118},
        .snare  = {  0,  0,  0,  0,255,  0,  0,118,  0,  0,  0,  0,255,  0,  0,118},
        .hihat  = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .perc   = {255,  0,  0,192,255,  0,  0,192,255,  0,  0,192,255,  0,  0,192},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 10, .recommendedBpm = 120
    },
    // Ska (9 source patterns: Measure A, Measure B, Break, Ska1, Ska2, Ska3, SkaBreak1, SkaBreak2, SkaBreak3)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {214,  0,  0,  0,118,  0,  0,  0,214,  0,  0,  0,118,  0,  0,  0},
        .snare  = { 89,  0,145,118,214,  0, 89,  0, 89,  0,118, 89,235, 89, 89, 89},
        .hihat  = {192,  0,192,  0,169,  0,192,  0,192,  0,192,  0,192,  0,192,  0},
        .perc   = {  0,  0,  0,  0, 55,  0, 89,  0,  0,  0, 55,  0,  0,  0, 55,  0},
        .accent = {145,  0,118,  0,145,  0,118,  0,145,  0,118,  0,169,  0,118,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 160
    },
    // Standard Breaks (4 source patterns: STANDARD BREAK 1, STANDARD BREAK 2, ROLLING BREAK, THE UNKNOWN DRUMMER)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0,  0, 97,  0,  0, 97, 97,  0,  0,255,  0,  0,  0,  0,  0},
        .snare  = {  0, 97,  0,  0,255,  0,  0, 97,  0,  0,  0,  0,255,  0,  0,  0},
        .hihat  = {208, 97,255,  0,255, 97,208,157,255, 97,208,  0,157, 97,255,  0},
        .perc   = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
    // Waltz (2 source patterns: Waltz1, Waltz2)
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {255,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .snare  = {  0,  0,  0,  0,255,  0,  0,  0,  0,  0,  0,  0,255,  0,  0,  0},
        .hihat  = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0},
        .perc   = {255,  0,  0,  0,  0,  0,  0,  0,  0,  0,157,  0,255,  0,  0,  0},
        .accent = {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,255,  0,  0,  0},
        .length = 16, .swingAmount = 0, .recommendedBpm = 140
    },

    // ========================================================================
    // HAND-AUTHORED STYLES (not derived from source data)
    // ========================================================================

    // Jazz (hand-authored — source patterns were 12-step triplet, commented out)
    // Classic jazz ride: spang-a-lang pattern. Kick feathers beats 1 and 3,
    // snare comps on 2 and 4 with ghost notes. Ride dominates on every beat
    // with off-beat emphasis (swing feel via swingAmount).
    // Think: Bill Evans trio, Miles Davis quintet, walking bass context.
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {220, 20, 30, 50, 40, 20, 30, 60,200, 20, 30, 80, 40, 20, 50, 60},
        .snare  = { 20, 30, 60, 40,180, 40, 70, 50, 30, 50, 80, 40,190, 50, 60, 90},
        .hihat  = {240, 40,200, 60,230, 50,210, 80,240, 50,200, 70,230, 50,210, 90},
        .perc   = { 30,  0, 20,  0, 40,  0, 20,  0, 30,  0, 20,  0, 50,  0, 30,  0},
        .accent = {180, 10, 10, 30,160, 20, 20, 40,140, 10, 20, 40,180, 20, 30, 50},
        .length = 16, .swingAmount = 8, .recommendedBpm = 130
    },

    // Brush Jazz (hand-authored)
    // Everything is quiet. The whole map lives in 60-150 range. No hit dominates.
    // Brushes swishing on snare (constant low-level presence), kick barely there,
    // ride ticking softly. Coffee shop, night scene in an RPG, 3am vibes.
    // The density knob here goes from "almost silence" to "gentle patter" —
    // never loud or busy, just more or less present.
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {140, 10, 15, 30, 20, 10, 15, 40,120, 10, 20, 50, 25, 15, 30, 35},
        .snare  = { 80, 70, 90, 75,130, 65, 85, 80, 75, 70, 95, 70,135, 70, 80,100},
        .hihat  = {150, 30,120, 40,140, 35,125, 50,145, 35,120, 45,140, 35,125, 55},
        .perc   = { 15,  0, 10,  0, 20,  0, 10,  0, 15,  0, 10,  0, 25,  0, 15,  0},
        .accent = { 90,  5,  5, 20,100, 10, 10, 25, 80,  5, 10, 25,110, 10, 15, 30},
        .length = 16, .swingAmount = 7, .recommendedBpm = 110
    },

    // Waltz Jazz (hand-authored)
    // 3/4 time (12 steps) with jazz feel. Ride on every beat with off-beat swing,
    // kick on 1, snare brushes 2 and 3. Ghost notes everywhere but very soft.
    // Think: "My Favorite Things", "Someday My Prince Will Come", wine bar RPG town.
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4 (unused in 3/4)  */
        .kick   = {230, 15, 25, 50, 30, 15, 40, 60,110, 20, 40, 70,  0,  0,  0,  0},
        .snare  = { 20, 30, 50, 40,170, 40, 60, 50, 30, 50,150, 60,  0,  0,  0,  0},
        .hihat  = {220, 35,180, 50,210, 40,190, 60,200, 40,180, 70,  0,  0,  0,  0},
        .perc   = { 20,  0, 15,  0, 30,  0, 15,  0, 25,  0, 20,  0,  0,  0,  0,  0},
        .accent = {150,  5, 10, 20,130, 10, 10, 30,100,  5, 15, 30,  0,  0,  0,  0},
        .length = 12, .swingAmount = 7, .recommendedBpm = 140
    },

    // Lo-fi / Bedroom (hand-authored)
    // Mac DeMarco, Homeshake, lo-fi hip hop. Slow, dreamy, barely awake.
    // Kick is minimal — just beat 1 and maybe a lazy one on 3. Snare is soft
    // with lots of ghost notes (the "texture" of the beat). Hihats are half-open,
    // inconsistent, some steps just missing. Heavy swing makes it lopsided.
    // At low density: just a kick and a snare, like someone tapping on a desk.
    // At high density: a warm, hazy groove that never feels urgent.
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {240, 10, 15, 25, 20, 10, 30, 50,160, 15, 40, 70, 20, 10, 50, 30},
        .snare  = { 15, 20, 40, 50,200, 30, 50, 70, 20, 40, 60, 45,210, 35, 55, 80},
        .hihat  = {160, 20,100, 25,130, 15,110, 30,150, 25, 90, 20,120, 15,100, 40},
        .perc   = { 10,  0,  5,  0, 10,  0,  5,  0, 15,  0,  5,  0, 10,  0,  5,  0},
        .accent = { 60,  0,  0, 10, 80,  5,  0, 15, 40,  0,  0, 10, 90,  5,  0, 20},
        .length = 16, .swingAmount = 6, .recommendedBpm = 78
    },

    // Jangle / Indie (hand-authored)
    // C86, Real Estate, early Mac DeMarco, Galaxie 500, The Pastels.
    // Ride cymbal carries the groove (not hihat). Kick only on 1 — anything more
    // feels too "rock". Snare on 2 and 4 but soft, with ghost notes that give it
    // a slightly off-kilter feel. Mid-tempo, straight (low swing), bright.
    // The perc track is ride cymbal (mapped to CY): constant 8ths, louder on beats.
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {250, 10, 10, 20, 15, 10, 15, 25, 90, 10, 15, 30, 15, 10, 20, 25},
        .snare  = { 10, 15, 35, 30,220, 20, 40, 35, 15, 25, 45, 30,230, 25, 40, 50},
        .hihat  = { 80, 30, 60, 25, 70, 25, 55, 20, 75, 30, 60, 20, 65, 25, 55, 30},
        .perc   = {230, 50,190, 60,210, 55,195, 70,225, 55,190, 65,210, 55,195, 75},
        .accent = {120,  5,  5, 10,100,  5,  5, 15, 80,  5,  5, 10,110,  5,  5, 15},
        .length = 16, .swingAmount = 2, .recommendedBpm = 118
    },

    // SNES / RPG (hand-authored)
    // Earthbound, Chrono Trigger, Secret of Mana, Terranigma.
    // Jazz-influenced but quantized to a grid (no swing — SNES had no shuffle).
    // Clean 8th-note hihats, simple kick/snare backbone, light percussion.
    // More structured than real jazz: kick on 1 and 3, snare on 2 and 4.
    // But with that JRPG flavor: occasional 16th ghost notes, cymbal accents
    // on transitions, a general brightness and clarity.
    // Tempo varies hugely in games (town=100, battle=140, overworld=120).
    {
        /*    1  .  .  .  2  .  .  .  3  .  .  .  4  .  .  .  */
        .kick   = {250, 10, 20, 40, 30, 10, 25, 50,220, 15, 30, 60, 25, 10, 35, 45},
        .snare  = { 10, 15, 30, 25,240, 15, 35, 30, 15, 20, 40, 25,245, 20, 30, 40},
        .hihat  = {220, 50,200, 55,210, 55,200, 60,215, 55,200, 55,210, 55,200, 65},
        .perc   = { 40,  0, 15, 10, 50,  0, 20, 15, 45,  0, 20, 10, 60,  0, 25, 15},
        .accent = {150,  5,  5, 15,130,  5,  5, 20,110,  5,  5, 15,160, 10, 10, 25},
        .length = 16, .swingAmount = 0, .recommendedBpm = 120
    },
};

#endif // PIXELSYNTH_RHYTHM_PROB_MAPS_H
